default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  user: Learn05
  host: localhost

development:
  <<: *default
  database: hackernews_development


test:
  <<: *default
  database: hackernews_test
